services:
  postgres-payment: # service name must match the hostname in .env file.
    image: postgres:17.3
    container_name: postgres-payment
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - ${DATABASE_DOCKER_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cart-demo

  payment-service:
    build:
      context: ${APP_BUILD_CONTEXT} # coolify use . value, maybe a bug.
      dockerfile: deployments/prd/Dockerfile
    expose:
      - 1323
    depends_on:
      postgres-payment:
        condition: service_healthy
    networks:
      - cart-demo

volumes:
  postgres-data:

networks:
  cart-demo:
    name: cart-demo
    driver: bridge
